-- Adds the latest World Cup restock quantities.
-- This is additive: it increases the listed size quantities instead of replacing current stock.

INSERT OR IGNORE INTO inventory (id, category, name, size, sizes_json, price, quantity, featured, featured_order, new_arrival, date_added, sort_order, photos, links)
VALUES
('world-spain-yamal-away', 'world', 'Lamine Yamal #19 | Spain 2026 World Cup Away', 'Medium', '{}', 55, 0, 0, 0, 1, CURRENT_TIMESTAMP, 170, '[{"src":"assets/inventory/world-spain-yamal-away-front.jpg","alt":"Lamine Yamal Spain 2026 World Cup away jersey front"},{"src":"assets/inventory/world-spain-yamal-away-back.jpg","alt":"Lamine Yamal Spain 2026 World Cup away jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('world-usa-pulisic-away', 'world', 'Christian Pulisic #10 | USA 2026 World Cup Away', 'Medium', '{}', 55, 0, 0, 0, 1, CURRENT_TIMESTAMP, 180, '[{"src":"assets/inventory/world-usa-pulisic-away-front.jpg","alt":"Christian Pulisic USA 2026 World Cup away jersey front"},{"src":"assets/inventory/world-usa-pulisic-away-back.jpg","alt":"Christian Pulisic USA 2026 World Cup away jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('world-norway-haaland-away', 'world', 'Erling Haaland #9 | Norway 2026 World Cup Away', 'Large', '{}', 55, 0, 0, 0, 1, CURRENT_TIMESTAMP, 190, '[{"src":"assets/inventory/world-norway-haaland-away-front.jpg","alt":"Erling Haaland Norway 2026 World Cup away jersey front"},{"src":"assets/inventory/world-norway-haaland-away-back.jpg","alt":"Erling Haaland Norway 2026 World Cup away jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('world-colombia-luis-diaz-home', 'world', 'Luis Diaz #7 | Colombia 2026 World Cup Home', 'Medium', '{}', 55, 0, 0, 0, 1, CURRENT_TIMESTAMP, 195, '[{"src":"assets/inventory/world-colombia-luis-diaz-home-front.jpg","alt":"Luis Diaz Colombia 2026 World Cup home jersey front"},{"src":"assets/inventory/world-colombia-luis-diaz-home-back.jpg","alt":"Luis Diaz Colombia 2026 World Cup home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('world-japan-blank-home', 'world', 'No Name/No Number | Japan 2026 World Cup Home', 'Medium', '{}', 55, 0, 0, 0, 1, CURRENT_TIMESTAMP, 196, '[{"src":"assets/inventory/world-japan-blank-home-front.jpg","alt":"Japan 2026 World Cup home jersey front with no name or number"},{"src":"assets/inventory/world-japan-blank-home-back.jpg","alt":"Japan 2026 World Cup home jersey back with no name or number"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('world-morocco-hakimi-away', 'world', 'Achraf Hakimi #2 | Morocco 2026 World Cup Away', 'Medium', '{}', 55, 0, 0, 0, 1, CURRENT_TIMESTAMP, 197, '[{"src":"assets/inventory/world-morocco-hakimi-away-front.jpg","alt":"Achraf Hakimi Morocco 2026 World Cup away jersey front"},{"src":"assets/inventory/world-morocco-hakimi-away-back.jpg","alt":"Achraf Hakimi Morocco 2026 World Cup away jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}');

UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 3), quantity = quantity + 3, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-portugal-ronaldo-home';
UPDATE inventory SET sizes_json = json_set(json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), '$.S', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.S'), 0) AS INTEGER) + 2), quantity = quantity + 4, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-argentina-messi-home';
UPDATE inventory SET sizes_json = json_set(json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 3), '$.S', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.S'), 0) AS INTEGER) + 1), quantity = quantity + 4, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-norway-haaland-home';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.L', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.L'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-norway-haaland-away';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 3), quantity = quantity + 3, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-england-bellingham-away';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 3), quantity = quantity + 3, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-spain-yamal-away';
UPDATE inventory SET sizes_json = json_set(json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 3), '$.S', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.S'), 0) AS INTEGER) + 2), quantity = quantity + 5, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-france-mbappe-home';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-france-olise-home';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-brazil-neymar-home';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-usa-pulisic-away';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-colombia-luis-diaz-home';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-japan-blank-home';
UPDATE inventory SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', CAST(COALESCE(json_extract(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M'), 0) AS INTEGER) + 2), quantity = quantity + 2, updated_at = CURRENT_TIMESTAMP WHERE id = 'world-morocco-hakimi-away';

INSERT INTO site_settings (key, value, updated_at)
VALUES ('inventory_updated_at', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP;
