-- Adds the 28 Medium jerseys received in the August 2026 drop.
-- The 12 photographed designs are new products (two each). The existing
-- Portugal and Manchester United Ronaldo products are set to two each.

INSERT OR IGNORE INTO inventory (id, category, name, size, sizes_json, price, quantity, featured, featured_order, new_arrival, date_added, sort_order, photos, links) VALUES
('club-real-madrid-bellingham-away-2627', 'club', 'Jude Bellingham #5 | Real Madrid 26/27 Away Kit', 'M', '{"M":2}', 40, 2, 0, 0, 1, '2026-08-12', 340, '[{"src":"assets/inventory/club-real-madrid-bellingham-away-2627-front.jpg","alt":"Jude Bellingham Real Madrid 26/27 away jersey front"},{"src":"assets/inventory/club-real-madrid-bellingham-away-2627-back.jpg","alt":"Jude Bellingham Real Madrid 26/27 away jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('club-psg-dembele-home-2627', 'club', 'Ousmane Dembele #10 | PSG 26/27 Home Kit', 'M', '{"M":2}', 40, 2, 0, 0, 1, '2026-08-12', 350, '[{"src":"assets/inventory/club-psg-dembele-home-2627-front.jpg","alt":"Ousmane Dembele PSG 26/27 home jersey front"},{"src":"assets/inventory/club-psg-dembele-home-2627-back.jpg","alt":"Ousmane Dembele PSG 26/27 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('club-arsenal-saka-home-2627', 'club', 'Bukayo Saka #7 | Arsenal 26/27 Home Kit', 'M', '{"M":2}', 40, 2, 0, 0, 1, '2026-08-12', 360, '[{"src":"assets/inventory/club-arsenal-saka-home-2627-front.jpg","alt":"Bukayo Saka Arsenal 26/27 home jersey front"},{"src":"assets/inventory/club-arsenal-saka-home-2627-back.jpg","alt":"Bukayo Saka Arsenal 26/27 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-england-beckham-home-9901', 'retro', 'David Beckham #7 | England 1999-2001 Home', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 370, '[{"src":"assets/inventory/retro-england-beckham-home-9901-front.jpg","alt":"David Beckham England 1999-2001 home jersey front"},{"src":"assets/inventory/retro-england-beckham-home-9901-back.jpg","alt":"David Beckham England 1999-2001 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-barcelona-cactus-jack', 'retro', 'Barcelona x Cactus Jack Jersey', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 380, '[{"src":"assets/inventory/retro-barcelona-cactus-jack-front.jpg","alt":"Barcelona x Cactus Jack jersey front"},{"src":"assets/inventory/retro-barcelona-cactus-jack-back.jpg","alt":"Barcelona x Cactus Jack jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-brazil-ronaldo-home-1998', 'retro', 'Ronaldo #9 | Brazil 1998 Home', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 390, '[{"src":"assets/inventory/retro-brazil-ronaldo-home-1998-front.jpg","alt":"Ronaldo Brazil 1998 home jersey front"},{"src":"assets/inventory/retro-brazil-ronaldo-home-1998-back.jpg","alt":"Ronaldo Brazil 1998 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-juventus-pogba-pink-1516', 'retro', 'Paul Pogba #10 | Juventus 2015/16 Pink', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 400, '[{"src":"assets/inventory/retro-juventus-pogba-pink-1516-front.jpg","alt":"Paul Pogba Juventus 2015/16 pink jersey front"},{"src":"assets/inventory/retro-juventus-pogba-pink-1516-back.jpg","alt":"Paul Pogba Juventus 2015/16 pink jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-france-zidane-home-2006', 'retro', 'Zinedine Zidane #10 | France 2006 Home', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 410, '[{"src":"assets/inventory/retro-france-zidane-home-2006-front.jpg","alt":"Zinedine Zidane France 2006 home jersey front"},{"src":"assets/inventory/retro-france-zidane-home-2006-back.jpg","alt":"Zinedine Zidane France 2006 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-brazil-ronaldinho-home-2002', 'retro', 'Ronaldinho #11 | Brazil 2002 Home', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 420, '[{"src":"assets/inventory/retro-brazil-ronaldinho-home-2002-front.jpg","alt":"Ronaldinho Brazil 2002 home jersey front"},{"src":"assets/inventory/retro-brazil-ronaldinho-home-2002-back.jpg","alt":"Ronaldinho Brazil 2002 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-chelsea-hazard-home-1415', 'retro', 'Eden Hazard #10 | Chelsea 2014/15 Home', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 430, '[{"src":"assets/inventory/retro-chelsea-hazard-home-1415-front.jpg","alt":"Eden Hazard Chelsea 2014/15 home jersey front"},{"src":"assets/inventory/retro-chelsea-hazard-home-1415-back.jpg","alt":"Eden Hazard Chelsea 2014/15 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-arsenal-henry-home-0506', 'retro', 'Thierry Henry #14 | Arsenal 2005/06 Home', 'M', '{"M":2}', 50, 2, 0, 0, 1, '2026-08-12', 440, '[{"src":"assets/inventory/retro-arsenal-henry-home-0506-front.jpg","alt":"Thierry Henry Arsenal 2005/06 home jersey front"},{"src":"assets/inventory/retro-arsenal-henry-home-0506-back.jpg","alt":"Thierry Henry Arsenal 2005/06 home jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}'),
('retro-ac-milan-kaka-home-0607-long', 'retro', 'Kaka #22 | AC Milan 2006/07 Home Long Sleeve', 'M', '{"M":2}', 55, 2, 0, 0, 1, '2026-08-12', 450, '[{"src":"assets/inventory/retro-ac-milan-kaka-home-0607-front.jpg","alt":"Kaka AC Milan 2006/07 home long sleeve jersey front"},{"src":"assets/inventory/retro-ac-milan-kaka-home-0607-back.jpg","alt":"Kaka AC Milan 2006/07 home long sleeve jersey back"}]', '{"depop":"https://www.depop.com/jerseysfrmjb/","ebay":"https://www.ebay.com/usr/jerseysfrmjb"}');

UPDATE inventory
SET sizes_json = json_set(COALESCE(NULLIF(sizes_json, ''), '{}'), '$.M', 2),
    quantity = 2,
    new_arrival = 1,
    date_added = '2026-08-12',
    updated_at = CURRENT_TIMESTAMP
WHERE id IN ('world-portugal-ronaldo-home', 'retro-ronaldo-united-short-0708');

INSERT INTO site_settings (key, value, updated_at)
VALUES ('august_2026_jersey_drop_28', 'applied', CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = 'applied', updated_at = CURRENT_TIMESTAMP;

INSERT INTO site_settings (key, value, updated_at)
VALUES ('inventory_updated_at', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET value = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP;
